{{- if .Values.containerDiskCredentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vmi.fullname" . }}-containerdisk-registry
  labels:
    {{- include "vmi.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "containerDiskPullSecret" . }}
{{- end }}
