{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "virtvnc.fullname" . }}
  labels:
    {{- include "virtvnc.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "virtvnc.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-vnc-console-access
  apiGroup: rbac.authorization.k8s.io
{{- end }}
