{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-vnc-console-access
  labels:
    {{- include "virtvnc.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachineinstances/console
      - virtualmachineinstances/vnc
    verbs:
      - get
{{- /*
The following are needed only for virtvnc to show list of running vms
and will not be needed when we customize the image to only access the
running vm we are deploying here.
*/}}
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
      - virtualmachineinstances
      - virtualmachineinstancereplicasets
      - virtualmachineinstancemigrations
    verbs:
      - get
      - list
      - watch
{{- end }}
