apiVersion: v1
kind: Service
metadata:
  name: {{ include "virtvnc.fullname" . }}-novnc
  labels:
    {{- include "virtvnc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8001
      protocol: TCP
      name: virtvnc
  selector:
    {{- include "virtvnc.selectorLabels" . | nindent 4 }}
{{- if .Values.unwebsockify.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "virtvnc.fullname" . }}-vnc
  labels:
    {{- include "virtvnc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.unwebsockify.service.type }}
  ports:
    - port: {{ .Values.unwebsockify.service.port }}
      targetPort: 5900
      protocol: TCP
      name: vnc
  selector:
    {{- include "virtvnc.selectorLabels" . | nindent 4 }}
{{- end }}
